name: Publish to pkg.go.dev

on:
  release:
    types: [published]

env:
    MANIFEST_PATH: .manifest.json

jobs:
  publish:
    runs-on: ubuntu-latest
      
    steps:        
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read module name
      id: read_module_name
      run: echo "module_name=$(jq -r '.config.languageOptions.go.goModuleName' $MANIFEST_PATH)" >> "$GITHUB_OUTPUT"

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'
      
    - name: Install package dependencies
      run: go mod download

    - name: Run list command to request indexing
      run: GOPROXY=proxy.golang.org go list -m ${{ steps.read_module_name.outputs.module_name }}
